seed: 1
tensorType: torch.cuda.FloatTensor
device: 'cuda'
gpus: 1
nodes:  1
nr: 0 #ranking within the nodels
world_size: 1
master_add: 'localhost'
master_port: '12355'
mode: 'train_valid' #'train'
is_continue: False
case: ddeform_seq004_dog_grid_jade_80k_res34_ctfvol1_bij_neus_rep3_4_rgb1.0_geo0.1
mcube_threshold: 0.0

general:
    base_dir: /jmain02/home/J2AD021/dxt03/mmm91-dxt03/Projects/NRGSurf
    base_exp_dir: /exp/
    recording: [
        '',
        'models',
        'models/LieAlgebra',
    ]

dataset:
    data_dir: /jmain02/home/J2AD021/dxt03/mmm91-dxt03/data/DeepDeform/seq004_dog # ./datasets/CASE_NAME/
    render_cameras_name: cameras_sphere.npz
    object_cameras_name: cameras_sphere.npz
    # Camera
    is_monocular: True # if the camera setting is monocular, set True

    # Depth
    use_depth: True
    # scale factor of depth
    # e.g. a pixel value of 1000 in the depth image corresponds to a distance of 1 meter from the camera.
    depth_scale: 1000.
    # Camera
    camera_trainable: True #False
    # Train skip
    trainskip: 1 #2 #10
    max_length: 200
    # image sampling strategy
    image_based: True


train:
    learning_rate: 5e-4
    learning_rate_alpha: 0.05
    end_iter: 80000 #120000
    batch_size: 1024 # 2048
    validate_resolution_level: 4
    warm_up_end: 5000
    anneal_end: 0
    igr_weight: 0.5
    mask_weight: 0.5
    # Depth
    geo_weight: 5.0
    angle_weight: 0.0 #0.5
    # scales. step function scale weights
    rgb_scale: [0.1, 1.0, 1.0]
    geo_scale: [10.0, 1.0, 0.1]
    regular_scale: [10.0, 10.0, 1.0]
    # our losses
    sdf_weight: 0.5
    fs_weight: 2.0
    surf_sdf: 0.0
    smooth_weight: 1.0
    smooth_std: 0.01
    tv_weight: 0.0 #10.0 #200.0 #1000.0 #500.0 #1.0 #100.0 #10.0
    akap_weight: 0.0
    latent_weight: 0.0
    temp_weight: 0.0
    # Deform
    use_deform: True
    use_topo: True
    use_bijective: True
    use_global_rigid: False
    use_app: False
    use_pts: False #True
    bij_type: ndr
    # Anneal. Coarse-to-Fine Optimization.
    max_pe_iter: 10000 #70000

    save_freq: 10000
    val_freq: 10000
    val_mesh_freq: 10000
    report_freq: 10000

    validate_idx: -1 # index of validation

    truncation: 0.08  # 0.08
    back_truncation: 0.5

    # image sampling strategy
    sample_sequential: False #True


test:
    test_batch_size: 3072


model:
    feature_grid:
        feat_dims: [32] #[14, 12, 6] #rep4  #[14, 8, 4] #rep3 ##[10, 4, 4]
        res: 34 #34 #134 #124 #149
        rgb_dim: 6
        pg_scale: [30000, 60000]
        feat_scale: [2] #[2] #[2, 1.2, 1]
        type: normal #['normal', 'Gaussian', 'MLP', 'AmbMLP', 'AmbMLPB']

    variance_network:
        init_val: 0.3

    neus_renderer:
        begin_n_samples: 64
        end_n_samples: 48
        important_begin_iter: 30000
        n_importance: 48
        up_sample_steps: 4
        perturb: 1.0

defaults:
    - deformation_network: bijective
    - topo_network: hypernerf
    - sdf_network: mini
    - rendering_network: mini
    #- override hydra/launcher: submitit_slurm #joblib